[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "proviso"
description = "Proviso requirements.txt management"
authors = [{name = "Ross McFarland", email = "rwmcfa1@gmail.com"}]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dynamic = ["version"]
keywords = ["octodns", "requirements", "dependency-resolution", "packaging"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Build Tools",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "build>=0.7.0",
    "hishel[httpx]>=0.1.0",
    "resolvelib>=1.0.0",
    "setuptools>=40.8.0",
    "unearth>=0.17.0",
]

[project.urls]
Homepage = "https://github.com/octodns/proviso"
Source = "https://github.com/octodns/proviso"
Issues = "https://github.com/octodns/proviso/issues"

[project.scripts]
proviso = "proviso.main:main"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-network",
]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-network",
    # we need to manually/explicitely bump major versions as they're
    # likely to result in formatting changes that should happen in their
    # own PR. This will basically happen yearly
    # https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy
    "black>=26.0.0,<27.0.0",
    "changelet",
    "isort>=5.11.5",
    "pyflakes>=2.2.0",
    "readme_renderer[md]>=26.0",
    "twine>=3.4.2",
]

[tool.setuptools.dynamic]
version = {attr = "proviso.__version__"}

[tool.setuptools.packages.find]
include = ["proviso*"]

[tool.black]
line-length=80
target-version = ["py310", "py311", "py312", "py313", "py314"]
skip-string-normalization=true
skip-magic-trailing-comma=true

[tool.isort]
profile = "black"
known_first_party="proviso"
# we'll often have a buTHIRDPARTYild directory which will trip isort up and make it think
# build is first-party, it's third
known_third_party=["build"]
line_length=80
sections="FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.pytest.ini_options]
filterwarnings = [
    'error',
]
pythonpath = "."
